stages:
  - build
  - deploy

variables:
  DOCKER_USERNAME: $DOCKER_USERNAME
  DOCKER_PASSWORD: $DOCKER_PASSWORD
  KUBECONFIG_DATA: $KUBECONFIG_DATA
  TELEGRAM_TOKEN_ID: $TELEGRAM_TOKEN_ID
  TELEGRAM_CHAT_ID: $TELEGRAM_CHAT_ID

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
    - docker build -t $DOCKER_USERNAME/chat-api-gateway:latest ./api-gateway
    - docker push $DOCKER_USERNAME/chat-api-gateway:latest
    - docker build -t $DOCKER_USERNAME/chat-socket-service:latest ./socket-service
    - docker push $DOCKER_USERNAME/chat-socket-service:latest
    - docker build -t $DOCKER_USERNAME/chat-notifications-service:latest ./notifications-service
    - docker push $DOCKER_USERNAME/chat-notifications-service:latest
  only:
    - main

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  before_script:
    - apk add --no-cache bash
    - mkdir -p ~/.kube
    - echo $KUBECONFIG_DATA | base64 -d > ~/.kube/config
    - kubectl config set-context --current --namespace=ecom-namespace
  script:
    - kubectl apply -f ./k8s/api-gateway-deployment.yaml
    - kubectl apply -f ./k8s/socket-service-deployment.yaml
    - kubectl apply -f ./k8s/notifications-service-deployment.yaml
  only:
    - main
