version: "3.8"

services:
  api_gateway:
    build:
      context: ./api_gateway
    ports:
      - "8080:3000"
    environment:
      - HTTP_PORT=3000
      - SOCKET_SERVICE_URL=ws://socket_service:3002/ws
      - DATABASE_URL=postgresql://root:password@postgres:5432/ecom?sslmode=disable
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - ACCESS_TOKEN_EXPIRES_IN=1h
      - REFRESH_TOKEN_EXPIRES_IN=87600h
      - ACCESS_JWT_SECRET=sadlasmdkamfksfksdms
      - REFRESH_JWT_SECRET=fghfghfgsefqxxceqeddc

    depends_on:
      - postgres
      - rabbitmq
    restart: unless-stopped

  notifications_service:
    build:
      context: ./notifications_service
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - EMAIL_ADDRESS=chatius101@gmail.com
      - EMAIL_PASSWORD="oycg ssdj jpsg cpwb"
      - BOT_TOKEN=7338324481:AAEJS7-7kDQRrnn0NBSeCwJPaiJT7SyBlEs
      - CHAT_ID=-1002161138641
    depends_on:
      - postgres
      - rabbitmq
    restart: unless-stopped

  socket_service:
    build:
      context: ./socket_service
    environment:
      - HTTP_PORT=3002
    depends_on:
      - rabbitmq
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecom
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
