version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  kafka:
    hostname: kafka
    image: bitnami/kafka:latest
    restart: always
    env_file:
      - kafka/kafka-variables.env
    depends_on:
      - zookeeper
    expose:
      - "9092"
      - "8082"
      - "8083"
    ports:
      - "9092:9092"
      - "8082:8082"
      - "8083:8083"

  zookeeper:
    hostname: zookeeper
    image: bitnami/zookeeper:latest
    restart: always
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - kafka
