basePath: /
host: localhost:3000
info:
  contact:
    email: 9gUOv@example.com
    name: API Support
    url: http://www.swagger.io/support
  description: API Gateway for chat app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: API Gateway
  version: "1.0"
paths: {}
schemes:
- http
swagger: "2.0"
