apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: ecom-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: ciscapello/chat-api-gateway:latest
          envFrom:
            - configMapRef:
                name: ecom-config
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: ecom-namespace
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 3000
      nodePort: 30080
  selector:
    app: api-gateway
