name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and push api-gateway image
        run: |
          docker build -t $DOCKER_USERNAME/chat-api-gateway:latest ./api-gateway
          docker push $DOCKER_USERNAME/chat-api-gateway:latest

      - name: Build and push socket-service image
        run: |
          docker build -t $DOCKER_USERNAME/chat-socket-service:latest ./socket-service
          docker push $DOCKER_USERNAME/chat-socket-service:latest

      - name: Build and push notifications-service image
        run: |
          docker build -t $DOCKER_USERNAME/chat-notifications-service:latest ./notifications-service
          docker push $DOCKER_USERNAME/chat-notifications-service:latest

      - name: Setup kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: "v1.18.0"

      - name: Create .kube directory
        run: |
          mkdir -p $HOME/.kube

      - name: Decode and configure KUBECONFIG
        run: |
          echo "${KUBECONFIG_DATA}" | base64 --decode > $HOME/.kube/config
          kubectl config set-context --current --namespace=ecom-namespace

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f ./k8s/api-gateway-deployment.yaml
          kubectl apply -f ./k8s/socket-service-deployment.yaml
          kubectl apply -f ./k8s/notifications-service-deployment.yaml

      - name: Send Telegram message
        uses: metalpoch/telegram-alerts-action@v1
        if: success()
        with:
          bot-token-id: ${{ secrets.TELEGRAM_TOKEN_ID }}
          chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}
          text: "<b>✅ Deployment Successful!</b>
            Repository: ${{ github.repository }}.
            Branch: ${{ github.ref_name }}..
            <a href='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'>View Details</a>"
          parse-mode: HTML
          disable-notification: false
          disable-web-page-preview: false
